language: python
python:
  - "3.4"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
#

# Setup anaconda
before_install:
  # Install apsw which refuses to by on pypi
  - git clone https://github.com/rogerbinns/apsw.git && cd apsw
#  - python setup.py fetch --missing-checksum-ok --all build --enable-all-extensions  install && cd ..
  - python setup.py fetch --missing-checksum-ok --all build --enable-all-extensions install && cd ..
  # Install MCL
  - wget http://micans.org/mcl/src/mcl-latest.tar.gz && tar xvvf mcl-latest.tar.gz
  - cd $(find . -name 'mcl-*' -type d | head -n 1) && ./configure --prefix=$HOME/.local && make && make install && cd ..
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.local/lib/
  # Intall hdf5
  - wget http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.16.tar && tar xvvf hdf5-1.8.16.tar
  - cd hdf5-1.8.16/ && ./configure --prefix=$HOME/.local && make &> /dev/null && make install && export HDF5_DIR=$HOME/.local && cd ..
  # upgrade to new pip with wheels
  - pip install pip --upgrade
  - PIP_ARGS="-I --trusted-host lovelace.cs.umn.edu --find-links=http://lovelace.cs.umn.edu/schaefer/wheelhouse/ --use-wheel --allow-external --allow-insecure"
  - pip install $PIP_ARGS -r requirements.txt
  - pip install tables
  - pip install pytest==2.7.3 -I
# Install packages
install:
  - python setup.py install
  # import camoco to compile the pyx modules
  - python -c 'import camoco as co;'
# command to run tests, e.g. python setup.py test
script:
  - py.test  tests/test_Locus.py -v
  - py.test  tests/test_RefGen.py -v
#  - py.test  tests/test_Term.py -v
  - py.test  tests/test_Expr.py -v
  - py.test  tests/test_COB.py -v
