sudo: required

language: python

python:
  - "3.4"

services:
  - docker

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
#
#
before_install:
  - docker build -t camoco .

script:
  - docker run -v cobdata:/cobdata camoco -c "cd /src/Camoco/ && py.test-3 -v tests/test_RefGen.py"
  - docker run -v cobdata:/cobdata camoco -c "cd /src/Camoco/ && py.test-3 -v tests/test_Term.py"
  - docker run -v cobdata:/cobdata camoco -c "cd /src/Camoco/ && py.test-3 -v tests/test_Expr.py"
  - docker run -v cobdata:/cobdata camoco -c "cd /src/Camoco/ && py.test-3 -v tests/test_COB.py"
