language: python
python:
  - "3.4"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors

# Install packages
env:
    - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.camoco/lib PATH=$PATH:$HOME/.camoco/bin:$HOME/.camoco/conda/bin
install:
  - bash install.sh
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - source activate camoco
  - python setup.py install
# command to run tests, e.g. python setup.py test
script:  
  - export PATH=$HOME/.camoco/bin:$PATH
  - py.test  tests -v  
