language: python
python:
  - "3.4"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors

# Install packages
install:
  - bash install.sh
  - export LD_LIBRARY_PATH=/home/travis/.camoco/lib:$LD_LIBRARY_PATH
  - export PATH=/home/travis/.camoco/bin:$PATH
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - source activate camoco
  - python setup.py install
# command to run tests, e.g. python setup.py test
script:  
  - py.test  tests -v --cov camoco 
after_sucess:
  - coveralls
