language: python
python:
  - "3.4"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors

# Install packages
install:
  - bash install.sh
  # import camoco to compile the pyx modules
  - python -c 'import camoco as co;'
# command to run tests, e.g. python setup.py test
script:  
  - py.test  tests -v --cov camoco 
after_sucess:
  - coveralls
