sudo: required

language: python

python:
  - "3.4"

services:
  - docker

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
#
#
before_install:
  - docker build -t camoco .
  - docker run -it --name='camoco' -v cobdata:/cobdata camoco

script:
  - py.test-3  tests/test_Locus.py -v
  - py.test-3  tests/test_RefGen.py -v
  - py.test-3  tests/test_Term.py -v
  - py.test-3  tests/test_Expr.py -v
  - py.test-3  tests/test_COB.py -v
